services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-prompt-app
    restart: unless-stopped
    ports:
      - "3030:3000" # Backend API
      - "3031:3001" # Frontend
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/ai_prompt_app?authSource=admin&directConnection=true
      - PORT=3000
      - FRONTEND_PORT=3001
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - OLLAMA_ENDPOINT=http://ollama:11434
      - OLLAMA_MODEL=llama3.1:latest
      - OLLAMA_TEMPERATURE=0.7
      - OLLAMA_MAX_TOKENS=500
      - OLLAMA_TIMEOUT=30000
    depends_on:
      - mongodb
      - ollama
    networks:
      - ai-prompt-network

  ollama:
    image: ollama/ollama:latest
    container_name: ai-prompt-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ai-prompt-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  ollama-pull:
    image: ollama/ollama:latest
    container_name: ai-prompt-ollama-pull
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    command: >
      sh -c "
        echo 'Waiting for Ollama service to be ready...' &&
        sleep 10 &&
        echo 'Pulling llama3.1:latest model...' &&
        ollama pull llama3.1:latest &&
        echo 'Model pull completed successfully!'
      "
    networks:
      - ai-prompt-network
    restart: "no"

  mongodb:
    image: mongo:7.0
    container_name: ai-prompt-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: ai_prompt_app
    command: [--auth]
    volumes:
      - mongodb_data:/data/db
      - ./scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - ai-prompt-network

  mongo-express:
    image: mongo-express:1.0.0
    container_name: ai-prompt-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: password123
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password123
      ME_CONFIG_BASICAUTH: true
    depends_on:
      - mongodb
    networks:
      - ai-prompt-network

volumes:
  mongodb_data:
  ollama_data:

networks:
  ai-prompt-network:
    driver: bridge
