version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-prompt-app
    restart: unless-stopped
    ports:
      - "3000:3000" # Backend API
      - "3001:3001" # Frontend
    environment:
      - NODE_ENV=development
      - PORT=3000
      - FRONTEND_PORT=3001
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./node_modules:/app/node_modules
